// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Expectativas_de_Mercado.Migrations.Migrations
{
    [DbContext(typeof(RegisterContext))]
    partial class RegisterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Expectativas_de_Mercado.Model.Aggregates.ExpectativasMercado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaseCalculo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Data")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IndicadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Maximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Minimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroRespondentes")
                        .HasColumnType("int");

                    b.Property<string>("Reuniao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndicadorId");

                    b.ToTable("ExpectativasMercado", (string)null);
                });

            modelBuilder.Entity("Expectativas_de_Mercado.Model.Core.Indicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Indicador", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "IPCA"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "IGP-M"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Selic"
                        });
                });

            modelBuilder.Entity("Expectativas_de_Mercado.Model.Aggregates.ExpectativasMercado", b =>
                {
                    b.HasOne("Expectativas_de_Mercado.Model.Core.Indicador", null)
                        .WithMany("ExpectativasMercados")
                        .HasForeignKey("IndicadorId");

                    b.OwnsOne("Expectativas_de_Mercado.Model.ValueObjects.DesvioPadrao", "DesvioPadrao", b1 =>
                        {
                            b1.Property<Guid>("ExpectativasMercadoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DesvioPadrao");

                            b1.HasKey("ExpectativasMercadoId");

                            b1.ToTable("ExpectativasMercado");

                            b1.WithOwner()
                                .HasForeignKey("ExpectativasMercadoId");
                        });

                    b.OwnsOne("Expectativas_de_Mercado.Model.ValueObjects.Media", "Media", b1 =>
                        {
                            b1.Property<Guid>("ExpectativasMercadoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Media");

                            b1.HasKey("ExpectativasMercadoId");

                            b1.ToTable("ExpectativasMercado");

                            b1.WithOwner()
                                .HasForeignKey("ExpectativasMercadoId");
                        });

                    b.OwnsOne("Expectativas_de_Mercado.Model.ValueObjects.Mediana", "Mediana", b1 =>
                        {
                            b1.Property<Guid>("ExpectativasMercadoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Mediana");

                            b1.HasKey("ExpectativasMercadoId");

                            b1.ToTable("ExpectativasMercado");

                            b1.WithOwner()
                                .HasForeignKey("ExpectativasMercadoId");
                        });

                    b.Navigation("DesvioPadrao")
                        .IsRequired();

                    b.Navigation("Media")
                        .IsRequired();

                    b.Navigation("Mediana")
                        .IsRequired();
                });

            modelBuilder.Entity("Expectativas_de_Mercado.Model.Core.Indicador", b =>
                {
                    b.Navigation("ExpectativasMercados");
                });
#pragma warning restore 612, 618
        }
    }
}
